name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.8'


    - name: Install Python 3.8 for windows
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install python --version 3.8.0
        export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
    
    - name: Install cibuildwheel
      run: |
        python3 -m pip install cibuildwheel==1.3.0
    
    - name: Install cffi
      run: |
        python3 -m pip install cffi

    - name: Build wheel
      run: |
        python3 -m cibuildwheel --output-dir wheelhouse

    - uses: actions/upload-artifact@v1
      with:
        name: wheels
        path: ./wheelhouse
